version: '3'
services:
  tests:
    build: .
    depends_on:
      - selenium
    environment:
      SELENIDE_REMOTE: "http://selenium:4444/wd/hub"
      SELENIDE_BROWSER: "chrome"
  selenium:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
    shm_size: 2gb